# Generated by Django 4.2.26 on 2025-11-22 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False, verbose_name='专辑编号')),
                ('album_title', models.CharField(max_length=192, verbose_name='专辑名称')),
                ('release_date', models.DateField(default='1970-01-01', verbose_name='发行日期')),
                ('cover_url', models.CharField(default='/images/default_album_cover.jpg', max_length=255, verbose_name='专辑封面路径')),
                ('description', models.CharField(blank=True, max_length=3072, null=True, verbose_name='专辑简介')),
            ],
            options={
                'verbose_name': '专辑',
                'verbose_name_plural': '专辑',
                'db_table': 'Album',
            },
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('singer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='歌手编号')),
                ('singer_name', models.CharField(max_length=60, verbose_name='歌手名称')),
                ('type', models.CharField(choices=[('男', '男'), ('女', '女'), ('组合', '组合')], max_length=2, verbose_name='歌手类型')),
                ('country', models.CharField(blank=True, max_length=20, null=True, verbose_name='国籍')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('introduction', models.CharField(blank=True, max_length=3072, null=True, verbose_name='歌手简介')),
            ],
            options={
                'verbose_name': '歌手',
                'verbose_name_plural': '歌手',
                'db_table': 'Singer',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False, verbose_name='歌曲编号')),
                ('song_title', models.CharField(max_length=192, verbose_name='歌曲名称')),
                ('duration', models.IntegerField(verbose_name='歌曲时长')),
                ('file_url', models.CharField(max_length=255, verbose_name='音频文件路径')),
                ('play_count', models.IntegerField(default=0, verbose_name='歌曲播放总次数')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.album', verbose_name='所属专辑')),
            ],
            options={
                'verbose_name': '歌曲',
                'verbose_name_plural': '歌曲',
                'db_table': 'Song',
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='日志编号')),
                ('action', models.CharField(max_length=255, verbose_name='操作内容')),
                ('target_table', models.CharField(blank=True, max_length=64, null=True, verbose_name='被操作数据表名')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='被操作记录ID')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('result', models.CharField(choices=[('success', 'success'), ('fail', 'fail')], max_length=10, verbose_name='操作结果状态')),
            ],
            options={
                'db_table': 'SystemLog',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户编号')),
                ('user_name', models.CharField(max_length=60, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='加密存储密码')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女'), ('其他', '其他')], default='其他', max_length=2, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='所在地区')),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='用户邮箱')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('profile', models.CharField(blank=True, max_length=768, null=True, verbose_name='个人简介')),
                ('status', models.CharField(choices=[('正常', '正常'), ('封禁中', '封禁中')], default='正常', max_length=3, verbose_name='账号状态')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Songlist',
            fields=[
                ('songlist_id', models.AutoField(primary_key=True, serialize=False, verbose_name='歌单编号')),
                ('songlist_title', models.CharField(max_length=192, verbose_name='歌单名称')),
                ('description', models.CharField(max_length=3072, verbose_name='歌单简介')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('cover_url', models.CharField(default='/images/default_songlist_cover.jpg', max_length=255, verbose_name='封面路径')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='创建者ID')),
            ],
            options={
                'verbose_name': '歌单',
                'verbose_name_plural': '歌单',
                'db_table': 'Songlist',
            },
        ),
        migrations.CreateModel(
            name='PlayHistory',
            fields=[
                ('play_id', models.AutoField(primary_key=True, serialize=False, verbose_name='播放记录编号')),
                ('play_time', models.DateTimeField(auto_now_add=True, verbose_name='播放时间')),
                ('play_duration', models.IntegerField(verbose_name='实际播放时长（秒）')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.song', verbose_name='播放歌曲')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='播放用户')),
            ],
            options={
                'db_table': 'PlayHistory',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favorite_id', models.AutoField(primary_key=True, serialize=False, verbose_name='收藏记录编号')),
                ('target_type', models.CharField(choices=[('song', 'song'), ('album', 'album'), ('songlist', 'songlist')], max_length=10, verbose_name='收藏对象类型')),
                ('target_id', models.IntegerField(verbose_name='收藏对象ID')),
                ('favorite_time', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='收藏用户')),
            ],
            options={
                'db_table': 'Favorite',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论编号')),
                ('target_type', models.CharField(choices=[('song', 'song'), ('album', 'album'), ('songlis', 'songlis')], max_length=10, verbose_name='评论目标类型')),
                ('content', models.CharField(max_length=300, verbose_name='评论内容')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('parent_id', models.IntegerField(blank=True, null=True, verbose_name='父评论ID')),
                ('status', models.CharField(choices=[('审核中', '审核中'), ('举报中', '举报中'), ('正常', '正常')], max_length=3, verbose_name='评论状态')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='评论用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'Comment',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='singer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.singer', verbose_name='所属歌手'),
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_time', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='app.user', verbose_name='被关注用户')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='app.user', verbose_name='关注者用户')),
            ],
            options={
                'db_table': 'UserFollow',
                'unique_together': {('follower', 'followed')},
            },
        ),
        migrations.CreateModel(
            name='SongSinger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.singer', verbose_name='歌手ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.song', verbose_name='歌曲ID')),
            ],
            options={
                'db_table': 'Song_Singer',
                'unique_together': {('song', 'singer')},
            },
        ),
        migrations.CreateModel(
            name='SonglistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.song', verbose_name='歌曲ID')),
                ('songlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.songlist', verbose_name='歌单ID')),
            ],
            options={
                'db_table': 'Songlist_Song',
                'unique_together': {('songlist', 'song')},
            },
        ),
        migrations.CreateModel(
            name='SingerFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_time', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.singer', verbose_name='被关注歌手')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='关注用户')),
            ],
            options={
                'db_table': 'SingerFollow',
                'unique_together': {('user', 'singer')},
            },
        ),
    ]
