# Generated by Django 4.2.26 on 2025-12-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='singer_id',
            new_name='singer',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='album_id',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='songlist',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='target_id',
            field=models.IntegerField(default=1, verbose_name='评论目标ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='visibility',
            field=models.CharField(choices=[('私密', '私密'), ('仅关注者可见', '仅关注者可见'), ('所有人可见', '所有人可见')], default='所有人可见', max_length=8, verbose_name='信息可见性'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='target_type',
            field=models.CharField(choices=[('song', 'song'), ('album', 'album'), ('songlist', 'songlist')], max_length=10, verbose_name='评论目标类型'),
        ),
        migrations.AlterField(
            model_name='songlist',
            name='description',
            field=models.CharField(blank=True, max_length=3072, null=True, verbose_name='歌单简介'),
        ),
    ]
